import * as dotenv from 'dotenv';

dotenv.config();
export interface ConfigParameters {
  PORT: string;
  REGION: string;
  ACCESS_KEY_ID: string;
  SECRET_ACCESS_KEY: string;
  TABLE_NAMES: TableNames;
  JWT_KEY: string;
  ONLINE_APPOINTMENT_KEY?: string;
  MONGO_DB_NAME: string;
  SUPER_TENANT_KEY?: string;
  BUCKET_NAME: string;
}
export interface ErrorMessages {
  AUTH_ERROR: string;
  BLANK_INPUT: string;
  INCORRECT_PASSWORD: string;
  TOKEN_UNAVAILABLE: string;
  PHONE_EXISTS: string;
  LIKE_EXISTS: string;
  NOT_LIKED: string;
  ADHAAR_NUMBER_ALREADY_PRESENT: string;
  PAN_NUMBER_ALREADY_PRESENT: string;
  DRIVING_LICENCE_NUMBER_ALREADY_PRESENT: string;
  TENANT_EXISTS: string;
  DATA_NOT_EXISTS: string;
  FORM_NAME_EXISTS: string;
}
export interface SuccessMessages {
  FILE_SUCCESS: string;
  USER_CREDENTIAL_SUCCESS: string;
  LOGIN_SUCCESS: string;
  TOKEN_GENERATION_SUCCESS: string;
  KYC_SUBMISSION_SUCCESS: string;
  LIKE_UPDATED: string;
  HEALTH_SUBMISSION_SUCCESS: string;
  SIGNUP_SUCCESS: string;
}
export interface TableNames {
  FORM_CONFIG_SCHEMA: string;
  PATIENT_REGISTRATION: string;
  REFERENCE_LOOKUP: string;
  DB_OBJECT_NAME: string;
  TENANT_SETUP: string;
  TRAIL_TABLE: string;
  WEBPART: string;
  ORGANOGRAM: string;
  SEARCH_BUILDER: string;
  MENU: string;
  CUSTOM_SOURCE_MAPPING: string;
  ROLE_PERMISSION: string;
  WORKFLOW: string;
  FACILITY_MASTER: string;
  PATIENT: string;
  PATIENT_VISIT: string;
  VITALS: string;
  SEQUENCE: string;
  ROLE_GROUP: string
  PASSWORD_POLICY: string;
  USER: string;
  EMPLOYEE_SETUP: string;
  EMAIL_TRAIL: string;
  LOOKUP_MAPPING: string;
  SYSTEM_GLOBAL_SETUP: string;
  APPOINTMENT_SLOT_SETUP: string;
  WEBHOOKS: string;
  ERROR_LOGS: string;
  REPORT_BUILDER: string;
  TARIFF_SETUP: string;
  SERVICES_SETUP: string;
  PAYER_MASTER: string
  PROVIDER_APPOINTMENT_DETAILS: string;
  APPOINTMENT_BOOKING_SLOTS: string;
  CARD_MASTER: string;
  BILLING_MASTER: string;
  WIDGETS_SETUP: string;
  ASSETS: string;
  PATIENT_REGISTRATION_EMR: string;
  // MEDICINE_MASTER: string;
  PATIENT_SERVICES_SETUP: string;
  DOCTORS_FAVOURITES: string;
  PATIENT_ENCOUNTER: string;
  RECURRENCE_RULES: string;
  CHIEF_COMPLAINTS_MASTER: string;
  AUTOGENERATE_SCHEMA: string;
  PRODUCER_DATA_LOGS: string;
  CONSUMER_DATA_LOGS: string;
  MULTI_LINGUAL: string;
  CROSS_TAB: string;
  DEFAULT_EXPORT: string;
  RULE_ENGINE: string;
  VITALS_GRAPH_CONFIGURATION: string;
  PATIENT_INVESTIGATION_HISTORY: string;
  FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: string;
  WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: string;
  WORKFLOW_PREVIOUS_VERSIONS: string;
  TASK_CONFIGURATION: string;
  COUNT_CONFIG: string;
  TASK_ASSIGNMENT_HISTORY: string;
  FIELD_CONFIG: string;
  GROUP_PARAMETER: string;
  LOGIN_SESSIONS: string;
  LOGIN_ACTIVITY_LOGS: string;
  LIBRARY: string;
  REFERENCE_LOOKUP_OLD_VERSIONS: string;
  TEMPLATE_BUILDER: string;
  DASHBOARD_CONFIG: string;
  VACCINE_MASTER_DB: string;
  NOTIFICATION_VENDOR: string;
  NOTIFICATION_VENDOR_SERVICE_CONFIG: string;
  NOTIFICATION_QUEUE: string;
  NOTIFICATION_SENT: string;
  NOTIFICATION_FAILURE: string;
  NOTIFICATION_TEMPLATE: string;
  EPISODIC_TEMPLATE: string;
  SESSION_TEMPLATE: string;
  TARIFF_SERVICES: string;
  EMR_DATA_ATTRIBUTES_SETUP:string;
}



export const NETWORK = process.env.NETWORK; // Set a default value if NETWORK is not provided in .env

const CONFIG_PARA: { [key: string]: ConfigParameters } = {
  TEST: {
    PORT: "5002",
    REGION: process.env.AWS_REGION!,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID!,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY!,
    JWT_KEY: process.env.JWT_KEY!,
    ONLINE_APPOINTMENT_KEY: process.env.ONLINE_APPOINTMENT_KEY!,
    SUPER_TENANT_KEY: process.env.SUPER_TENANT_KEY!,
    MONGO_DB_NAME: "AKHIL_SYSTEMS_DEV",
    BUCKET_NAME: "-sdlc-dev",
    TABLE_NAMES: {
      DEFAULT_EXPORT: "DEFAULT_EXPORT",
      PATIENT_REGISTRATION_EMR: "PATIENT_REGISTRATION_EMR",
      FORM_CONFIG_SCHEMA: "FORM_CONFIG_SCHEMA",
      PATIENT_REGISTRATION: "PATIENT_REGISTRATION_DB",
      REFERENCE_LOOKUP: "REFERENCE_LOOKUP",
      DB_OBJECT_NAME: "DB_OBJECT_NAME",
      TENANT_SETUP: "TENANT_SETUP",
      TRAIL_TABLE: "TRAIL_TABLE",
      WEBPART: "WEBPART",
      ORGANOGRAM: "ORGANOGRAM",
      SEARCH_BUILDER: "SEARCH_BUILDER",
      MENU: "MENU",
      CUSTOM_SOURCE_MAPPING: "CUSTOM_SOURCE_MAPPING",
      ROLE_PERMISSION: "ROLE_PERMISSION",
      WORKFLOW: "WORKFLOW",
      FACILITY_MASTER: "FACILITY_MASTER",
      PATIENT: "PATIENT",
      PATIENT_VISIT: "PATIENT_VISIT",
      VITALS: "VITALS",
      SEQUENCE: "SEQUENCE",
      ROLE_GROUP: "ROLE_GROUP",
      PASSWORD_POLICY: "PASSWORD_POLICY",
      USER: "USER",
      EMPLOYEE_SETUP: "EMPLOYEE_SETUP",
      EMAIL_TRAIL: "EMAIL_TRAIL",
      LOOKUP_MAPPING: "LOOKUP_MAPPING",
      SYSTEM_GLOBAL_SETUP: "SYSTEM_GLOBAL_SETUP",
      APPOINTMENT_SLOT_SETUP: "APPOINTMENT_SLOT_SETUP",
      WEBHOOKS: "WEBHOOKS",
      ERROR_LOGS: "ERROR_LOGS",
      REPORT_BUILDER: "REPORT_BUILDER",
      TARIFF_SETUP: "TARIFF_SETUP",
      SERVICES_SETUP: "SERVICES_SETUP",
      PAYER_MASTER: "PAYER_MASTER",
      PROVIDER_APPOINTMENT_DETAILS: "PROVIDER_APPOINTMENT_DETAILS",
      WORKFLOW_PREVIOUS_VERSIONS: "WORKFLOW_PREVIOUS_VERSIONS",
      APPOINTMENT_BOOKING_SLOTS: "APPOINTMENT_BOOKING_SLOTS",
      CARD_MASTER: "CARD_MASTER",
      BILLING_MASTER: "BILLING_MASTER",
      WIDGETS_SETUP: "WIDGETS_SETUP",
      ASSETS: "ASSETS",
      // MEDICINE_MASTER: "MEDICINE_MASTER",
      PATIENT_SERVICES_SETUP: "PATIENT_SERVICES_SETUP",
      DOCTORS_FAVOURITES: "DOCTORS_FAVOURITES",
      PATIENT_ENCOUNTER: "PATIENT_ENCOUNTER",
      RECURRENCE_RULES: "RECURRENCE_RULES",
      CHIEF_COMPLAINTS_MASTER: "CHIEF_COMPLAINTS_MASTER",
      AUTOGENERATE_SCHEMA: "AUTOGENERATE_SCHEMA",
      PRODUCER_DATA_LOGS: "PRODUCER_DATA_LOGS",
      CONSUMER_DATA_LOGS: "CONSUMER_DATA_LOGS",
      MULTI_LINGUAL: "MULTI_LINGUAL",
      CROSS_TAB: "CROSS_TAB",
      RULE_ENGINE: "RULE_ENGINE",
      VITALS_GRAPH_CONFIGURATION: "VITALS_GRAPH_CONFIGURATION",
      PATIENT_INVESTIGATION_HISTORY: "PATIENT_INVESTIGATION_HISTORY",
      FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      TASK_CONFIGURATION: "TASK_CONFIGURATION",
      COUNT_CONFIG: "COUNT_CONFIG",
      TASK_ASSIGNMENT_HISTORY: "TASK_ASSIGNMENT_HISTORY",
      FIELD_CONFIG: "FIELD_CONFIG",
      GROUP_PARAMETER: "GROUP_PARAMETER",
      LOGIN_SESSIONS: "LOGIN_SESSIONS",
      LOGIN_ACTIVITY_LOGS: "LOGIN_ACTIVITY_LOGS",
      LIBRARY: "LIBRARY",
      REFERENCE_LOOKUP_OLD_VERSIONS: "REFERENCE_LOOKUP_OLD_VERSIONS",
      TEMPLATE_BUILDER: "TEMPLATE_BUILDER",
      DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
      VACCINE_MASTER_DB: "VACCINE_MASTER_DB",
      NOTIFICATION_VENDOR: "NOTIFICATION_VENDOR",
      NOTIFICATION_VENDOR_SERVICE_CONFIG: "NOTIFICATION_VENDOR_SERVICE_CONFIG",
      NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
      NOTIFICATION_SENT: 'NOTIFICATION_SENT',
      NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
      NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
      EPISODIC_TEMPLATE: "EPISODIC_TEMPLATE",
      SESSION_TEMPLATE: "SESSION_TEMPLATE",
      TARIFF_SERVICES: "TARIFF_SERVICES",
      EMR_DATA_ATTRIBUTES_SETUP:"EMR_DATA_ATTRIBUTES_SETUP"
    }
  },
  DEMO: {
    PORT: "5001",
    REGION: process.env.AWS_REGION!,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID!,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY!,
    JWT_KEY: process.env.JWT_KEY!,
    ONLINE_APPOINTMENT_KEY: process.env.ONLINE_APPOINTMENT_KEY!,
    SUPER_TENANT_KEY: process.env.SUPER_TENANT_KEY!,
    MONGO_DB_NAME: "AKHIL_SYSTEMS_DEMO",
    BUCKET_NAME: "-sdlc-dev",
    TABLE_NAMES: {
      DEFAULT_EXPORT: "DEFAULT_EXPORT",
      PATIENT_REGISTRATION_EMR: "PATIENT_REGISTRATION_EMR",
      FORM_CONFIG_SCHEMA: "FORM_CONFIG_SCHEMA",
      PATIENT_REGISTRATION: "PATIENT_REGISTRATION_DB",
      REFERENCE_LOOKUP: "REFERENCE_LOOKUP",
      DB_OBJECT_NAME: "DB_OBJECT_NAME",
      TENANT_SETUP: "TENANT_SETUP",
      TRAIL_TABLE: "TRAIL_TABLE",
      WEBPART: "WEBPART",
      ORGANOGRAM: "ORGANOGRAM",
      SEARCH_BUILDER: "SEARCH_BUILDER",
      MENU: "MENU",
      CUSTOM_SOURCE_MAPPING: "CUSTOM_SOURCE_MAPPING",
      WORKFLOW_PREVIOUS_VERSIONS: "WORKFLOW_PREVIOUS_VERSIONS",
      ROLE_PERMISSION: "ROLE_PERMISSION",
      WORKFLOW: "WORKFLOW",
      FACILITY_MASTER: "FACILITY_MASTER",
      PATIENT: "PATIENT",
      PATIENT_VISIT: "PATIENT_VISIT",
      VITALS: "VITALS",
      SEQUENCE: "SEQUENCE",
      ROLE_GROUP: "ROLE_GROUP",
      PASSWORD_POLICY: "PASSWORD_POLICY",
      USER: "USER",
      EMPLOYEE_SETUP: "EMPLOYEE_SETUP",
      EMAIL_TRAIL: "EMAIL_TRAIL",
      LOOKUP_MAPPING: "LOOKUP_MAPPING",
      SYSTEM_GLOBAL_SETUP: "SYSTEM_GLOBAL_SETUP",
      APPOINTMENT_SLOT_SETUP: "APPOINTMENT_SLOT_SETUP",
      WEBHOOKS: "WEBHOOKS",
      ERROR_LOGS: "ERROR_LOGS",
      REPORT_BUILDER: "REPORT_BUILDER",
      TARIFF_SETUP: "TARIFF_SETUP",
      SERVICES_SETUP: "SERVICES_SETUP",
      PAYER_MASTER: "PAYER_MASTER",
      PROVIDER_APPOINTMENT_DETAILS: "PROVIDER_APPOINTMENT_DETAILS",
      APPOINTMENT_BOOKING_SLOTS: "APPOINTMENT_BOOKING_SLOTS",
      CARD_MASTER: "CARD_MASTER",
      BILLING_MASTER: "BILLING_MASTER",
      WIDGETS_SETUP: "WIDGETS_SETUP",
      ASSETS: "ASSETS",
      // MEDICINE_MASTER: "MEDICINE_MASTER",
      PATIENT_SERVICES_SETUP: "PATIENT_SERVICES_SETUP",
      DOCTORS_FAVOURITES: "DOCTORS_FAVOURITES",
      PATIENT_ENCOUNTER: "PATIENT_ENCOUNTER",
      RECURRENCE_RULES: "RECURRENCE_RULES",
      CHIEF_COMPLAINTS_MASTER: "CHIEF_COMPLAINTS_MASTER",
      AUTOGENERATE_SCHEMA: "AUTOGENERATE_SCHEMA",
      PRODUCER_DATA_LOGS: "PRODUCER_DATA_LOGS",
      CONSUMER_DATA_LOGS: "CONSUMER_DATA_LOGS",
      MULTI_LINGUAL: "MULTI_LINGUAL",
      CROSS_TAB: "CROSS_TAB",
      RULE_ENGINE: "RULE_ENGINE",
      VITALS_GRAPH_CONFIGURATION: "VITALS_GRAPH_CONFIGURATION",
      PATIENT_INVESTIGATION_HISTORY: "PATIENT_INVESTIGATION_HISTORY",
      FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      TASK_CONFIGURATION: "TASK_CONFIGURATION",
      COUNT_CONFIG: "COUNT_CONFIG",
      TASK_ASSIGNMENT_HISTORY: "TASK_ASSIGNMENT_HISTORY",
      FIELD_CONFIG: "FIELD_CONFIG",
      GROUP_PARAMETER: "GROUP_PARAMETER",
      LOGIN_SESSIONS: "LOGIN_SESSIONS",
      LOGIN_ACTIVITY_LOGS: "LOGIN_ACTIVITY_LOGS",
      LIBRARY: "LIBRARY",
      REFERENCE_LOOKUP_OLD_VERSIONS: "REFERENCE_LOOKUP_OLD_VERSIONS",
      TEMPLATE_BUILDER: "TEMPLATE_BUILDER",
      DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
      VACCINE_MASTER_DB: "VACCINE_MASTER_DB",
      NOTIFICATION_VENDOR: "NOTIFICATION_VENDOR",
      NOTIFICATION_VENDOR_SERVICE_CONFIG: "NOTIFICATION_VENDOR_SERVICE_CONFIG",
      NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
      NOTIFICATION_SENT: 'NOTIFICATION_SENT',
      NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
      NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
      EPISODIC_TEMPLATE: "EPISODIC_TEMPLATE",
      SESSION_TEMPLATE: "SESSION_TEMPLATE",
      TARIFF_SERVICES: "TARIFF_SERVICES",
      EMR_DATA_ATTRIBUTES_SETUP:"EMR_DATA_ATTRIBUTES_SETUP"
    }
  },
  DEV: {
    PORT: "5003",
    REGION: process.env.AWS_REGION,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID!,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY!,
    JWT_KEY: process.env.JWT_KEY!,
    ONLINE_APPOINTMENT_KEY: process.env.ONLINE_APPOINTMENT_KEY!,
    SUPER_TENANT_KEY: process.env.SUPER_TENANT_KEY!,
    MONGO_DB_NAME: "AKHIL_SYSTEMS_TEST",
    BUCKET_NAME: "-sdlc-test",
    TABLE_NAMES: {
      DEFAULT_EXPORT: "DEFAULT_EXPORT",
      PATIENT_REGISTRATION_EMR: "PATIENT_REGISTRATION_EMR",
      FORM_CONFIG_SCHEMA: "FORM_CONFIG_SCHEMA",
      PATIENT_REGISTRATION: "PATIENT_REGISTRATION_DB",
      REFERENCE_LOOKUP: "REFERENCE_LOOKUP",
      DB_OBJECT_NAME: "DB_OBJECT_NAME",
      TENANT_SETUP: "TENANT_SETUP",
      TRAIL_TABLE: "TRAIL_TABLE",
      WEBPART: "WEBPART",
      ORGANOGRAM: "ORGANOGRAM",
      SEARCH_BUILDER: "SEARCH_BUILDER",
      WORKFLOW_PREVIOUS_VERSIONS: "WORKFLOW_PREVIOUS_VERSIONS",
      MENU: "MENU",
      CUSTOM_SOURCE_MAPPING: "CUSTOM_SOURCE_MAPPING",
      ROLE_PERMISSION: "ROLE_PERMISSION",
      WORKFLOW: "WORKFLOW",
      FACILITY_MASTER: "FACILITY_MASTER",
      PATIENT: "PATIENT",
      PATIENT_VISIT: "PATIENT_VISIT",
      VITALS: "VITALS",
      SEQUENCE: "SEQUENCE",
      ROLE_GROUP: "ROLE_GROUP",
      PASSWORD_POLICY: "PASSWORD_POLICY",
      USER: "USER",
      EMPLOYEE_SETUP: "EMPLOYEE_SETUP",
      EMAIL_TRAIL: "EMAIL_TRAIL",
      LOOKUP_MAPPING: "LOOKUP_MAPPING",
      SYSTEM_GLOBAL_SETUP: "SYSTEM_GLOBAL_SETUP",
      APPOINTMENT_SLOT_SETUP: "APPOINTMENT_SLOT_SETUP",
      WEBHOOKS: "WEBHOOKS",
      ERROR_LOGS: "ERROR_LOGS",
      REPORT_BUILDER: "REPORT_BUILDER",
      TARIFF_SETUP: "TARIFF_SETUP",
      SERVICES_SETUP: "SERVICES_SETUP",
      PROVIDER_APPOINTMENT_DETAILS: "PROVIDER_APPOINTMENT_DETAILS",
      APPOINTMENT_BOOKING_SLOTS: "APPOINTMENT_BOOKING_SLOTS",
      PAYER_MASTER: "PAYER_MASTER",
      CARD_MASTER: "CARD_MASTER",
      BILLING_MASTER: "BILLING_MASTER",
      WIDGETS_SETUP: "WIDGETS_SETUP",
      ASSETS: "ASSETS",
      // MEDICINE_MASTER: "MEDICINE_MASTER",
      PATIENT_SERVICES_SETUP: "PATIENT_SERVICES_SETUP",
      DOCTORS_FAVOURITES: "DOCTORS_FAVOURITES",
      PATIENT_ENCOUNTER: "PATIENT_ENCOUNTER",
      RECURRENCE_RULES: "RECURRENCE_RULES",
      CHIEF_COMPLAINTS_MASTER: "CHIEF_COMPLAINTS_MASTER",
      AUTOGENERATE_SCHEMA: "AUTOGENERATE_SCHEMA",
      PRODUCER_DATA_LOGS: "PRODUCER_DATA_LOGS",
      CONSUMER_DATA_LOGS: "CONSUMER_DATA_LOGS",
      MULTI_LINGUAL: "MULTI_LINGUAL",
      CROSS_TAB: "CROSS_TAB",
      RULE_ENGINE: "RULE_ENGINE",
      VITALS_GRAPH_CONFIGURATION: "VITALS_GRAPH_CONFIGURATION",
      PATIENT_INVESTIGATION_HISTORY: "PATIENT_INVESTIGATION_HISTORY",
      FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      TASK_CONFIGURATION: "TASK_CONFIGURATION",
      COUNT_CONFIG: "COUNT_CONFIG",
      TASK_ASSIGNMENT_HISTORY: "TASK_ASSIGNMENT_HISTORY",
      FIELD_CONFIG: "FIELD_CONFIG",
      GROUP_PARAMETER: "GROUP_PARAMETER",
      LOGIN_SESSIONS: "LOGIN_SESSIONS",
      LOGIN_ACTIVITY_LOGS: "LOGIN_ACTIVITY_LOGS",
      LIBRARY: "LIBRARY",
      REFERENCE_LOOKUP_OLD_VERSIONS: "REFERENCE_LOOKUP_OLD_VERSIONS",
      TEMPLATE_BUILDER: "TEMPLATE_BUILDER",
      DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
      VACCINE_MASTER_DB: "VACCINE_MASTER_DB",
      NOTIFICATION_VENDOR: "NOTIFICATION_VENDOR",
      NOTIFICATION_VENDOR_SERVICE_CONFIG: "NOTIFICATION_VENDOR_SERVICE_CONFIG",
      NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
      NOTIFICATION_SENT: 'NOTIFICATION_SENT',
      NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
      NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
      EPISODIC_TEMPLATE: "EPISODIC_TEMPLATE",
      SESSION_TEMPLATE: "SESSION_TEMPLATE",
      TARIFF_SERVICES: "TARIFF_SERVICES",
      EMR_DATA_ATTRIBUTES_SETUP:"EMR_DATA_ATTRIBUTES_SETUP"
    }
  },
  UAT: {
    PORT: "5004",
    REGION: process.env.AWS_REGION,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID!,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY!,
    JWT_KEY: process.env.JWT_KEY!,
    ONLINE_APPOINTMENT_KEY: process.env.ONLINE_APPOINTMENT_KEY!,
    SUPER_TENANT_KEY: process.env.SUPER_TENANT_KEY!,
    MONGO_DB_NAME: "AKHIL_SYSTEMS_UAT",
    BUCKET_NAME: "-sdlc-uat",
    TABLE_NAMES: {
      DEFAULT_EXPORT: "DEFAULT_EXPORT",
      PATIENT_REGISTRATION_EMR: "PATIENT_REGISTRATION_EMR",
      FORM_CONFIG_SCHEMA: "FORM_CONFIG_SCHEMA",
      PATIENT_REGISTRATION: "PATIENT_REGISTRATION_DB",
      REFERENCE_LOOKUP: "REFERENCE_LOOKUP",
      DB_OBJECT_NAME: "DB_OBJECT_NAME",
      TENANT_SETUP: "TENANT_SETUP",
      TRAIL_TABLE: "TRAIL_TABLE",
      WEBPART: "WEBPART",
      ORGANOGRAM: "ORGANOGRAM",
      WORKFLOW_PREVIOUS_VERSIONS: "WORKFLOW_PREVIOUS_VERSIONS",
      SEARCH_BUILDER: "SEARCH_BUILDER",
      MENU: "MENU",
      CUSTOM_SOURCE_MAPPING: "CUSTOM_SOURCE_MAPPING",
      ROLE_PERMISSION: "ROLE_PERMISSION",
      WORKFLOW: "WORKFLOW",
      FACILITY_MASTER: "FACILITY_MASTER",
      PATIENT: "PATIENT",
      PATIENT_VISIT: "PATIENT_VISIT",
      VITALS: "VITALS",
      SEQUENCE: "SEQUENCE",
      ROLE_GROUP: "ROLE_GROUP",
      PASSWORD_POLICY: "PASSWORD_POLICY",
      USER: "USER",
      EMPLOYEE_SETUP: "EMPLOYEE_SETUP",
      EMAIL_TRAIL: "EMAIL_TRAIL",
      LOOKUP_MAPPING: "LOOKUP_MAPPING",
      SYSTEM_GLOBAL_SETUP: "SYSTEM_GLOBAL_SETUP",
      APPOINTMENT_SLOT_SETUP: "APPOINTMENT_SLOT_SETUP",
      WEBHOOKS: "WEBHOOKS",
      ERROR_LOGS: "ERROR_LOGS",
      REPORT_BUILDER: "REPORT_BUILDER",
      TARIFF_SETUP: "TARIFF_SETUP",
      SERVICES_SETUP: "SERVICES_SETUP",
      PROVIDER_APPOINTMENT_DETAILS: "PROVIDER_APPOINTMENT_DETAILS",
      APPOINTMENT_BOOKING_SLOTS: "APPOINTMENT_BOOKING_SLOTS",
      PAYER_MASTER: "PAYER_MASTER",
      CARD_MASTER: "CARD_MASTER",
      BILLING_MASTER: "BILLING_MASTER",
      WIDGETS_SETUP: "WIDGETS_SETUP",
      ASSETS: "ASSETS",
      // MEDICINE_MASTER: "MEDICINE_MASTER",
      PATIENT_SERVICES_SETUP: "PATIENT_SERVICES_SETUP",
      DOCTORS_FAVOURITES: "DOCTORS_FAVOURITES",
      PATIENT_ENCOUNTER: "PATIENT_ENCOUNTER",
      RECURRENCE_RULES: "RECURRENCE_RULES",
      CHIEF_COMPLAINTS_MASTER: "CHIEF_COMPLAINTS_MASTER",
      AUTOGENERATE_SCHEMA: "AUTOGENERATE_SCHEMA",
      PRODUCER_DATA_LOGS: "PRODUCER_DATA_LOGS",
      CONSUMER_DATA_LOGS: "CONSUMER_DATA_LOGS",
      MULTI_LINGUAL: "MULTI_LINGUAL",
      CROSS_TAB: "CROSS_TAB",
      RULE_ENGINE: "RULE_ENGINE",
      VITALS_GRAPH_CONFIGURATION: "VITALS_GRAPH_CONFIGURATION",
      PATIENT_INVESTIGATION_HISTORY: "PATIENT_INVESTIGATION_HISTORY",
      FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      TASK_CONFIGURATION: "TASK_CONFIGURATION",
      COUNT_CONFIG: "COUNT_CONFIG",
      TASK_ASSIGNMENT_HISTORY: "TASK_ASSIGNMENT_HISTORY",
      FIELD_CONFIG: "FIELD_CONFIG",
      GROUP_PARAMETER: "GROUP_PARAMETER",
      LOGIN_SESSIONS: "LOGIN_SESSIONS",
      LOGIN_ACTIVITY_LOGS: "LOGIN_ACTIVITY_LOGS",
      LIBRARY: "LIBRARY",
      REFERENCE_LOOKUP_OLD_VERSIONS: "REFERENCE_LOOKUP_OLD_VERSIONS",
      TEMPLATE_BUILDER: "TEMPLATE_BUILDER",
      DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
      VACCINE_MASTER_DB: "VACCINE_MASTER_DB",
      NOTIFICATION_VENDOR: "NOTIFICATION_VENDOR",
      NOTIFICATION_VENDOR_SERVICE_CONFIG: "NOTIFICATION_VENDOR_SERVICE_CONFIG",
      NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
      NOTIFICATION_SENT: 'NOTIFICATION_SENT',
      NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
      NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
      EPISODIC_TEMPLATE: "EPISODIC_TEMPLATE",
      SESSION_TEMPLATE: "SESSION_TEMPLATE",
      TARIFF_SERVICES: "TARIFF_SERVICES",
      EMR_DATA_ATTRIBUTES_SETUP:"EMR_DATA_ATTRIBUTES_SETUP"
    }
  },
  PRE_PROD: {
    PORT: "5006",
    REGION: process.env.AWS_REGION,
    ACCESS_KEY_ID: process.env.ACCESS_KEY_ID!,
    SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY!,
    JWT_KEY: process.env.JWT_KEY!,
    ONLINE_APPOINTMENT_KEY: process.env.ONLINE_APPOINTMENT_KEY!,
    SUPER_TENANT_KEY: process.env.SUPER_TENANT_KEY!,
    MONGO_DB_NAME: "AKHIL_SYSTEMS_PRE_PROD",
    BUCKET_NAME: "-sdlc-pre-prod",
    TABLE_NAMES: {
      DEFAULT_EXPORT: "DEFAULT_EXPORT",
      PATIENT_REGISTRATION_EMR: "PATIENT_REGISTRATION_EMR",
      FORM_CONFIG_SCHEMA: "FORM_CONFIG_SCHEMA",
      PATIENT_REGISTRATION: "PATIENT_REGISTRATION_DB",
      REFERENCE_LOOKUP: "REFERENCE_LOOKUP",
      DB_OBJECT_NAME: "DB_OBJECT_NAME",
      TENANT_SETUP: "TENANT_SETUP",
      TRAIL_TABLE: "TRAIL_TABLE",
      WORKFLOW_PREVIOUS_VERSIONS: "WORKFLOW_PREVIOUS_VERSIONS",
      WEBPART: "WEBPART",
      ORGANOGRAM: "ORGANOGRAM",
      SEARCH_BUILDER: "SEARCH_BUILDER",
      MENU: "MENU",
      CUSTOM_SOURCE_MAPPING: "CUSTOM_SOURCE_MAPPING",
      ROLE_PERMISSION: "ROLE_PERMISSION",
      WORKFLOW: "WORKFLOW",
      FACILITY_MASTER: "FACILITY_MASTER",
      PATIENT: "PATIENT",
      PATIENT_VISIT: "PATIENT_VISIT",
      VITALS: "VITALS",
      SEQUENCE: "SEQUENCE",
      ROLE_GROUP: "ROLE_GROUP",
      PASSWORD_POLICY: "PASSWORD_POLICY",
      USER: "USER",
      EMPLOYEE_SETUP: "EMPLOYEE_SETUP",
      EMAIL_TRAIL: "EMAIL_TRAIL",
      LOOKUP_MAPPING: "LOOKUP_MAPPING",
      SYSTEM_GLOBAL_SETUP: "SYSTEM_GLOBAL_SETUP",
      APPOINTMENT_SLOT_SETUP: "APPOINTMENT_SLOT_SETUP",
      WEBHOOKS: "WEBHOOKS",
      ERROR_LOGS: "ERROR_LOGS",
      REPORT_BUILDER: "REPORT_BUILDER",
      TARIFF_SETUP: "TARIFF_SETUP",
      SERVICES_SETUP: "SERVICES_SETUP",
      PROVIDER_APPOINTMENT_DETAILS: "PROVIDER_APPOINTMENT_DETAILS",
      APPOINTMENT_BOOKING_SLOTS: "APPOINTMENT_BOOKING_SLOTS",
      PAYER_MASTER: "PAYER_MASTER",
      CARD_MASTER: "CARD_MASTER",
      BILLING_MASTER: "BILLING_MASTER",
      WIDGETS_SETUP: "WIDGETS_SETUP",
      ASSETS: "ASSETS",
      // MEDICINE_MASTER: "MEDICINE_MASTER",
      PATIENT_SERVICES_SETUP: "PATIENT_SERVICES_SETUP",
      DOCTORS_FAVOURITES: "DOCTORS_FAVOURITES",
      PATIENT_ENCOUNTER: "PATIENT_ENCOUNTER",
      RECURRENCE_RULES: "RECURRENCE_RULES",
      CHIEF_COMPLAINTS_MASTER: "CHIEF_COMPLAINTS_MASTER",
      AUTOGENERATE_SCHEMA: "AUTOGENERATE_SCHEMA",
      PRODUCER_DATA_LOGS: "PRODUCER_DATA_LOGS",
      CONSUMER_DATA_LOGS: "CONSUMER_DATA_LOGS",
      MULTI_LINGUAL: "MULTI_LINGUAL",
      CROSS_TAB: "CROSS_TAB",
      RULE_ENGINE: "RULE_ENGINE",
      VITALS_GRAPH_CONFIGURATION: "VITALS_GRAPH_CONFIGURATION",
      PATIENT_INVESTIGATION_HISTORY: "PATIENT_INVESTIGATION_HISTORY",
      FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "FORM_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS: "WEBPART_CONFIG_SCHEMA_PREVIOUS_VERSIONS",
      TASK_CONFIGURATION: "TASK_CONFIGURATION",
      COUNT_CONFIG: "COUNT_CONFIG",
      TASK_ASSIGNMENT_HISTORY: "TASK_ASSIGNMENT_HISTORY",
      FIELD_CONFIG: "FIELD_CONFIG",
      GROUP_PARAMETER: "GROUP_PARAMETER",
      LOGIN_SESSIONS: "LOGIN_SESSIONS",
      LOGIN_ACTIVITY_LOGS: "LOGIN_ACTIVITY_LOGS",
      LIBRARY: "LIBRARY",
      REFERENCE_LOOKUP_OLD_VERSIONS: "REFERENCE_LOOKUP_OLD_VERSIONS",
      TEMPLATE_BUILDER: "TEMPLATE_BUILDER",
      DASHBOARD_CONFIG: "DASHBOARD_CONFIG",
      VACCINE_MASTER_DB: "VACCINE_MASTER_DB",
      NOTIFICATION_VENDOR: "NOTIFICATION_VENDOR",
      NOTIFICATION_VENDOR_SERVICE_CONFIG: "NOTIFICATION_VENDOR_SERVICE_CONFIG",
      NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
      NOTIFICATION_SENT: 'NOTIFICATION_SENT',
      NOTIFICATION_FAILURE: 'NOTIFICATION_FAILURE',
      NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
      EPISODIC_TEMPLATE: "EPISODIC_TEMPLATE",
      SESSION_TEMPLATE: "SESSION_TEMPLATE",
      TARIFF_SERVICES: "TARIFF_SERVICES",
      EMR_DATA_ATTRIBUTES_SETUP:"EMR_DATA_ATTRIBUTES_SETUP"
    }
  },
};

export const ERROR_MESSAGES: ErrorMessages = {
  AUTH_ERROR: "Authorisation Failed!",
  BLANK_INPUT: "Input fields cannot be blank!",
  INCORRECT_PASSWORD: "Password incorrect!",
  TOKEN_UNAVAILABLE: "JWT token not available!",
  PHONE_EXISTS: 'Phone number exists.',
  LIKE_EXISTS: "You have already liked this post.",
  NOT_LIKED: "You have not yet liked this post.",
  ADHAAR_NUMBER_ALREADY_PRESENT: "Adhaar number already present.",
  PAN_NUMBER_ALREADY_PRESENT: "Pan number already present.",
  DRIVING_LICENCE_NUMBER_ALREADY_PRESENT: "Driving licence number already present.",
  TENANT_EXISTS: "Tenant already exists.",
  DATA_NOT_EXISTS: "Data not found.",
  FORM_NAME_EXISTS: "Form name already exists."
};

export const SUCCESS_MESSAGES: SuccessMessages = {
  FILE_SUCCESS: 'File uploaded successfully',
  USER_CREDENTIAL_SUCCESS: 'User credential created successfully',
  LOGIN_SUCCESS: 'Login successfully.',
  TOKEN_GENERATION_SUCCESS: 'Token generated successfully.',
  KYC_SUBMISSION_SUCCESS: 'KYC submitted successfully',
  LIKE_UPDATED: 'Like Updated.',
  HEALTH_SUBMISSION_SUCCESS: 'Health details submitted successfully',
  SIGNUP_SUCCESS: 'Signup successfully.'
}

export const PORT_NAME = CONFIG_PARA[NETWORK].PORT;
export const AWS_REGION = CONFIG_PARA[NETWORK].REGION;
export const AWS_ACCESS_KEY_ID = CONFIG_PARA[NETWORK].ACCESS_KEY_ID;
export const AWS_SECRET_ACCESS_KEY = CONFIG_PARA[NETWORK].SECRET_ACCESS_KEY;
export const TABLE_NAMES: TableNames = CONFIG_PARA[NETWORK].TABLE_NAMES;
export const JWT_KEY = CONFIG_PARA[NETWORK].JWT_KEY;
export const ONLINE_APPOINTMENT_KEY = CONFIG_PARA[NETWORK].ONLINE_APPOINTMENT_KEY;
export const DBService = "mongoDBService";
export const ManagerService = "DBConnectionManager";
export const MONGO_URI = process.env.MONGO_URL;
export const MONGO_DB_NAME: string = CONFIG_PARA[NETWORK].MONGO_DB_NAME;
export const SUPER_TENANT_KEY = CONFIG_PARA[NETWORK].SUPER_TENANT_KEY;
export const BUCKET_NAME: string = CONFIG_PARA[NETWORK].BUCKET_NAME;
export const MAIL_PASSWORD = process.env.MAIL_PASSWORD;
export const SESSION_SECRET = process.env.SESSION_SECRET;
export const date = new Date();
export const TOKEN_ENCRYPTION_KEY = process.env.TOKEN_ENCRYPTION_KEY;
export const STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  COMPLETED: "completed",
  IN_PROGRESS: "in progress",
  CANCELLED: "cancelled",
  REASSIGNED: "reassigned",
  DRAFT: "D",
  SIGNED: "S",
  ASSIGNED: "N",
  NOT_APPLICABLE: "NA",
};
export const HIS_NETWORK = {
  TEST: process.env.TEST_NETWORK,
  DEMO: process.env.DEMO_NETWORK,
  DEV: process.env.DEV_NETWORK,
  UAT: process.env.UAT_NETWORK,
  PRE_PROD: process.env.PRE_PROD_NETWORK,
  PROD: process.env.PROD_NETWORK,
};

export const HIS_MONGO_DB_NAME = {
  TEST: process.env.TEST_MONGO_DB_NAME,
  DEMO: process.env.DEMO_MONGO_DB_NAME,
  UAT: process.env.UAT_MONGO_DB_NAME,
  PRE_PROD: process.env.PRE_PROD_MONGO_DB_NAME,
  PROD: process.env.PROD_MONGO_DB_NAME,
  DEV: process.env.DEV_MONGO_DB_NAME,
};

export const HIS_MONGODB_URI = {
  TEST: process.env.TEST_MONGO_URL,
  DEMO: process.env.DEMO_MONGO_URL,
  UAT: process.env.UAT_MONGO_URL,
  PRE_PROD: process.env.PRE_PROD_MONGO_URL,
  PROD: process.env.PROD_MONGO_URL,
  DEV: process.env.DEV_MONGO_URL,
}


export const MAIL_ID = process.env.MAIL_ID;
